### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by fredrikekre** [chengchingwen/Transformers.jl#1]
Please enable CI for this repository, e.g. Travis/Appveyor.

**Comment by chengchingwen** [comment]
Thanks for the issue. Could you give me some guide on how to enable the CI?

**Comment by fredrikekre** [comment]
Most packages use Travis (tests on Linux and macOS) and AppVeyor (runs on Windows) but if this package does not use binary dependencies or other platform specific things I would say it is enough to use Travis. To enable Travis you:
1. Enable https://github.com/marketplace/travis-ci for this repository
2. Create a `.travis.yml` config file in the repository, see e.g. https://github.com/fredrikekre/Literate.jl/blob/master/.travis.yml (you can skip the last part about building docs if you don't use that setup).

**Comment by chengchingwen** [comment]
@fredrikekre Did I did it right? The result is at [here](https://travis-ci.com/chengchingwen/Transformers.jl). The osx got lots of weird log and terminate.

**Comment by fredrikekre** [comment]
Yea, looks good! Don't you get those warnings when you run the tests locally?

**Comment by chengchingwen** [comment]
No, I work on a linux machine which never showed the warnings. It looks pretty weird because the warnings are complaining about a method is overwritten by itself.

**Comment by fredrikekre** [comment]
Strange. I can try later on macos locally.

**Comment by chengchingwen** [comment]
@fredrikekre I fix the warning issue! that was due to macos use case-insensitive file system and the clone was failed (due to I have two files of same name with different cases). Just rename the file and all the CI passed. Tks!
