### ISSUE TITLE
Bert Cola Example Missing Import

### ISSUE THREAD

**Issue by jackn11** [chengchingwen/Transformers.jl#100]
In the example at the link below, line 36 yields the error that ```todevice``` is not defined. This is because there is no general import which includes that method such as ```using Transformers``` which includes that method in the file. This could easily be fixed by including  ```using Transformers``` at the top of the file.

https://github.com/chengchingwen/Transformers.jl/blob/master/example/BERT/cola/train.jl

**Comment by chengchingwen** [comment]
Because it's not the top-level entry. Please refer to the [instructions in the readme](https://github.com/chengchingwen/Transformers.jl/tree/master/example/BERT)
