### ISSUE TITLE
Error Pre-Compiling While Using Pluto

### ISSUE THREAD

**Issue by davidsonff** [chengchingwen/Transformers.jl#121]
I'm getting an error using Pluto that Transformers fails to pre-compile:

WARNING: Method definition (::Type{Strided.StridedView{T, N, A, F} where F<:Union{typeof(Base.adjoint), typeof(Base.conj), typeof(Base.identity), typeof(Base.transpose)} where A<:(DenseArray{T, N} where N where T) where N where T})(Base.PermutedDimsArrays.PermutedDimsArray{T, N, perm, iperm, AA} where AA<:(AbstractArray{T, N} where N where T) where iperm) where {T, N, perm} in module Strided at C:\Users\davidfr\.julia\packages\Strided\pDrSx\src\stridedview.jl:35 overwritten in module Torch at C:\Users\davidfr\.julia\packages\Pickle\Ro6BR\src\torch\torch_save.jl:37.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: ArgumentError: Unsupported keyword argument 'config'
Stacktrace:
  [1] var"@cuda"(__source__::LineNumberNode, __module__::Module, ex::Vararg{Any})
    @ CUDA C:\Users\davidfr\.julia\packages\CUDA\DfvRa\src\compiler\execution.jl:47
  [2] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
  [3] include(x::String)
    @ Transformers.HuggingFace C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\HuggingFace.jl:1
  [4] top-level scope
    @ C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\models\models.jl:68
  [5] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
  [6] include(x::String)
    @ Transformers.HuggingFace C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\HuggingFace.jl:1
  [7] top-level scope
    @ C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\HuggingFace.jl:20
  [8] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
  [9] include(x::String)
    @ Transformers C:\Users\davidfr\.julia\packages\Transformers\V363g\src\Transformers.jl:1
 [10] top-level scope
    @ C:\Users\davidfr\.julia\packages\Transformers\V363g\src\Transformers.jl:70
 [11] include
    @ .\Base.jl:419 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1554
 [13] top-level scope
    @ stdin:1
in expression starting at C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\models\utils.jl:69
in expression starting at C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\models\utils.jl:46
in expression starting at C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\models\models.jl:68
in expression starting at C:\Users\davidfr\.julia\packages\Transformers\V363g\src\huggingface\HuggingFace.jl:1
in expression starting at C:\Users\davidfr\.julia\packages\Transformers\V363g\src\Transformers.jl:1
in expression starting at stdin:1

**Comment by chengchingwen** [comment]
What version of Transformers.jl are you using? Could you update the package to the latest version, the issue should be fixed in some newer release.

**Comment by chengchingwen** [comment]
That's weird. Do you launch Pluto with the same environment?

**Comment by davidsonff** [comment]
I assume so? I am just using Pluto.run()? I think I updated all my packages (I'm a bit new to Julia). Could I be missing a dependency? I don't have CUDA installed as I'm using a company laptop currently?

**Comment by chengchingwen** [comment]
Could you try `using Pkg; Pkg.status()` within Pluto? This should give you the environment Pluto is using.

> Could I be missing a dependency? I don't have CUDA installed as I'm using a company laptop currently?

You don't need to have CUDA installed. The error is about a macro syntax change of the CUDA package.

**Comment by davidsonff** [comment]
It seems to be some problem with package compatibility. It keeps downgrading my version to 0.1.14. I think this is something on my end, so I will close this. Thank you for the help!

**Comment by chengchingwen** [comment]
Maybe try explicitly adding 0.1.24 and [pinning](https://pkgdocs.julialang.org/v1/managing-packages/#Pinning-a-package) Transformers.jl and redo the operation that cause the downgrade.
