### ISSUE TITLE
Tokenizer for MPNET model

### ISSUE THREAD

**Issue by MNLubov** [chengchingwen/Transformers.jl#135]
Hi @chengchingwen, 

Thanks for your fantastic package. I use it a lot. I was wondering if you've ever considered adding a tokenizer for the MPNet transformer model? This tokenizer is used in the most powerful sentence transformer model based on MPNET architecture. 
MPNET tokenizer is a little bit different from BERT tokenizer, but it [inherits from the BERT tokenizer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mpnet/tokenization_mpnet.py).

**Comment by chengchingwen** [comment]
Should be workable with v0.2.4.
