### ISSUE TITLE
Implementation of recommender system based on Transformers

### ISSUE THREAD

**Issue by marthinkondjeni** [chengchingwen/Transformers.jl#140]
I'm currently working on a project that involves implementing a recommender system based on Transformers. I would greatly appreciate any guidance or pointers related to implementing a recommender system using Transformers.

**Comment by chengchingwen** [comment]
I'm not familiar with recommender systerm. I'll say it might be better to find some paper of recommender system that use transformer with source code and reimplement them as a baseline.
