### ISSUE TITLE
update NNlib and Flux compat

### ISSUE THREAD

**Issue by CarloLucibello** [chengchingwen/Transformers.jl#153]
This package is incompatible with Flux 0.14 and NNlib 0.9. Can the compatibility be updated?

**Comment by chengchingwen** [comment]
What are the breaking changes beside dropping julia 1.6 and using package extension?

**Comment by CarloLucibello** [comment]
Just the extension thing. So NNlibCUDA is deprecated, and for CUDA support in Flux one has to explicitly load CUDA.jl

**Comment by CarloLucibello** [comment]
I think the only required change here is to drop `NNlibCUDA` and to increase julia compatibility to `>= 1.9`.

**Comment by CarloLucibello** [comment]
Julia 1.9 changed many things. I'm sure those interested in getting package updates are already using it.
On the other hand, it seems more problematic not to get Flux and NNlib updates if you have this package in your environment.

**Comment by originalsouth** [comment]
> Yes, but I'm a little worried about dropping julia `< 1.9`.

@chengchingwen can you please elaborate?

**Comment by chengchingwen** [comment]
@originalsouth Simply because julia 1.6 is the LTS version.

**Comment by originalsouth** [comment]
I guess most FluxML packages as Flux.jl has dropped that support already... perhaps an LTS branch for this repository can mediate the conflict of interests?

**Comment by johannes-fischer** [comment]
6 months later, any updates on updating Flux compat? I think this is long overdue
