### ISSUE TITLE
AMDGPU support

### ISSUE THREAD

**Issue by radudiaconu0** [chengchingwen/Transformers.jl#158]
Can we have amdgpu support?

**Comment by chengchingwen** [comment]
Shouldn't be hard to add. Generally it just needs to make sure a few functions, like [NeuralAttentionlib's gemm](https://github.com/chengchingwen/NeuralAttentionlib.jl/blob/2b9a568280a96ce8c2b00433c3c7dbf8aa7cf9dd/src/matmul/gpu.jl#L11), dispatch to the correct functions. But I don't have amdgpu to test.
