### ISSUE TITLE
please update compat bounds

### ISSUE THREAD

**Issue by CarloLucibello** [chengchingwen/Transformers.jl#175]
There are a lot of unmerged CompatHelper PRs in this repo.
@chengchingwen could you update the compact bounds, in particular the latest Flux and NNlib version?

**Comment by johannes-fischer** [comment]
Any plans for this?

**Comment by svilupp** [comment]
I believe this makes Transformers.jl uninstallable now. 

I'm not sure how it's possible, but I've tried from fresh environment and it fails in resolving. Clearly, some dependency has moved on :/

Example
```
]activate --temp
]add Transformers@0.2.8

   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:
 GPUCompiler [61eb1bfa] log:
 ├─possible versions are: 0.1.0-0.26.4 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 0.22.0-0.26.4 or uninstalled
 └─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.15.1-0.21.4 — no versions left
   └─CUDA [052768ef] log:
     ├─possible versions are: 0.1.0-5.3.1 or uninstalled
     ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-5.3.1] or uninstalled
     ├─restricted by compatibility requirements with Transformers [21ca0261] to versions: 3.10.0-5.3.1
     │ └─Transformers [21ca0261] log:
     │   ├─possible versions are: 0.0.1-0.2.8 or uninstalled
     │   └─restricted to versions 0.2.8 by an explicit requirement, leaving only versions: 0.2.8
     └─restricted by compatibility requirements with Flux [587475ba] to versions: 3.0.0-4.4.2, leaving only versions: 3.10.0-4.4.2
       └─Flux [587475ba] log:
         ├─possible versions are: 0.4.1-0.14.15 or uninstalled
         └─restricted by compatibility requirements with Transformers [21ca0261] to versions: 0.13.4-0.13.17
           └─Transformers [21ca0261] log: see above
```

**Comment by cpfiffer** [comment]
I spent a bit trying to chase down the compat issues today and _wow_ what an absolute nightmare. 

- GPUCompiler.jl is less of an issue thanks to [this](https://github.com/JuliaGPU/GPUCompiler.jl/commit/e18cdd240bf71cbc94d5fc7718ecaa4f122a19bd).
- A bigger issue is [NNlibCUDA.jl](https://github.com/FluxML/NNlibCUDA.jl/issues/72), which seems to be vaguely deprecated. Supposedly NNlib.jl contains all the functionality of NNlibCUDA.jl, but this may require some internal code changes and not just compat updates.

**Comment by cpfiffer** [comment]
Oh this is great, it doesn't seem like the package imports NNlibCUDA.jl anywhere, perhaps we can simply drop the compat. Experimenting.

**Comment by cpfiffer** [comment]
Opened #185, which should address some of this. Testing still ongoing.
