### ISSUE TITLE
HuggingFace Validation not working as expected

### ISSUE THREAD

**Issue by deveshjawla** [chengchingwen/Transformers.jl#195]
Hi Peter @chengchingwen,

Could you please help with the HuggingFace Validation not working as expected?

When trying to validate other models such Roberta, Bloom etc, the Validation works fine but I have added Distilbert and it give the following error.

````
[ Info: Loading python packages
[ Info: Python packages loaded successfully
[ Info: Load configure file in Python
[ Info: Load configure file in Julia
[ Info: Validate distilbert/distilbert-base-cased based model
[ Info: Loading based model in Python
[ Info: Python model loaded successfully
[ Info: Loading based model in Julia
┌ Error: Failed to load the model in Julia
└ @ Main ~/Projects/Transformers.jl/example/HuggingFaceValidation/utils.jl:2
Based Model: Error During Test at /Users/456828/Projects/Transformers.jl/example/HuggingFaceValidation/based_model.jl:6
  Got exception outside of a @test
  Unknown model type: distilbert
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:35
    [2] _get_model_type(model_type::Symbol)
      @ Transformers.HuggingFace ~/.julia/packages/Transformers/qH1VW/src/huggingface/models/models.jl:35
    [3] macro expansion
      @ ~/.julia/packages/Transformers/qH1VW/src/huggingface/models/models.jl:40 [inlined]
    [4] #1071#default_f
      @ ~/.julia/packages/ValSplit/Qe1Uy/src/ValSplit.jl:185 [inlined]
    [5] macro expansion
      @ ~/.julia/packages/ValSplit/Qe1Uy/src/ValSplit.jl:0 [inlined]
    [6] _valswitch
      @ ~/.julia/packages/ValSplit/Qe1Uy/src/ValSplit.jl:137 [inlined]
    [7] get_model_type
      @ ~/.julia/packages/ValSplit/Qe1Uy/src/ValSplit.jl:187 [inlined]
    [8] get_model_type(model_type::Symbol, task::Symbol)
      @ Transformers.HuggingFace ~/.julia/packages/Transformers/qH1VW/src/huggingface/models/models.jl:43 
````

However if I load the implementation of distilbert from REPL I am able to load it.

`Transformers.HuggingFace.load_model("distilbert/distilbert-base-cased", :model, state_dict; config= conf)`

````
HGFDistilBertModel(
  Chain(
    CompositeEmbedding(
      token = Embed(768, 28996),        # 22_268_928 parameters
      position = ApplyEmbed(.+, FixedLenPositionEmbed(768, 512), Main.Transformers.HuggingFace.distilbert_pe_indices(0,)),  # 393_216 parameters
      segment = ApplyEmbed(.+, Embed(768, 512), Main.Transformers.HuggingFace.bert_ones_like),  # 393_216 parameters
    ),
    DropoutLayer<nothing>(
      LayerNorm(768, ϵ = 1.0e-12),      # 1_536 parameters
    ),
  ),
  Transformer<6>(
    PostNormTransformerBlock(
      DropoutLayer<nothing>(
        SelfAttention(
          MultiheadQKVAttenOp(head = 12, p = nothing),
          Fork<3>(Dense(W = (768, 768), b = true)),  # 1_771_776 parameters
          Dense(W = (768, 768), b = true),  # 590_592 parameters
        ),
      ),
      LayerNorm(768, ϵ = 1.0e-12),      # 1_536 parameters
      DropoutLayer<nothing>(
        Chain(
          Dense(σ = NNlib.gelu, W = (768, 3072), b = true),  # 2_362_368 parameters
          Dense(W = (3072, 768), b = true),  # 2_360_064 parameters
        ),
      ),
      LayerNorm(768, ϵ = 1.0e-12),      # 1_536 parameters
    ),
  ),                  # Total: 96 arrays, 42_527_232 parameters, 162.238 MiB.
  Branch{(:pooled,) = (:hidden_state,)}(
    BertPooler(Dense(σ = NNlib.tanh_fast, W = (768, 768), b = true)),  # 590_592 parameters
  ),
)                   # Total: 103 arrays, 66_174_720 parameters, 252.448 MiB.`
```

**Comment by chengchingwen** [comment]
Can you check if the model correctly subtype `HuggingFace.HGFPreTrained{:distilbert}`? 

https://github.com/chengchingwen/Transformers.jl/blob/12ed656d75aa1d8f29f44145c9fed1e76a39bebe/src/huggingface/models/models.jl#L33-L36

**Comment by deveshjawla** [comment]
Thanks for your response.

Yes, The function `_get_model_type` returns the named tuple as expected from the REPL.

````
Transformers.HuggingFace._get_model_type(:distilbert)
(forcausallm = Main.Transformers.HuggingFace.HGFDistilBertForCausalLM, formaskedlm = Main.Transformers.HuggingFace.HGFDistilBertForMaskedLM, forquestionanswering = Main.Transformers.HuggingFace.HGFDistilBertForQuestionAnswering, forsequenceclassification = Main.Transformers.HuggingFace.HGFDistilBertForSequenceClassification, fortokenclassification = Main.Transformers.HuggingFace.HGFDistilBertForTokenClassification, model = Main.Transformers.HuggingFace.HGFDistilBertModel)
````

**Comment by chengchingwen** [comment]
So running the loader in REPL works successfully but running with the validation code failed? Could you check if the validation code is using the correct environment with your implementation (since there is a `Project.toml/Manifest.toml` in the validation code folder)?

**Comment by deveshjawla** [comment]
Hi Peter,

Thank you for your response.

I am running the Validation from the correct environment. For other models such as [FacebookAI/xlm-roberta-base](url)  or [distilbert/distilroberta-base](url) the validation does not error.

This is leading me to believe that my DistilBert implementation has issues. I also got the familiar warnings such as:
` Warning: startsym <s> not in vocabulary, this might cause problem.`

These are the same as in #163

**Comment by chengchingwen** [comment]
Those are different model types. `distilbert/distilroberta-base`, despite using the name "distilbert", [the model type is actually the same as normal roberta](https://huggingface.co/distilbert/distilroberta-base/blob/fb53ab8802853c8e4fbdbcd0529f21fc6f459b2b/config.json#L15). However, the case here is that [the model type is "distilbert"](https://huggingface.co/distilbert/distilbert-base-cased/blob/6ea81172465e8b0ad3fddeed32b986cdcdcffcf0/config.json#L12), as mentioned in the error inside `_get_model_type`.

Could you try to launch the REPL after the validation failed with the `-i` option? like `some/path/to/this/HuggingFaceValidation$ julia --project -i main.jl -s based_model distilbert/distilbert-base-cased` and run the code to load the model manually in that REPL?

I'm suspecting that it's just an environmental problem because the stacktrace shows the error was from the packages folder instead of a forked path (which I believe is `/Users/456828/Projects/Transformers.jl/`):

```
 [2] _get_model_type(model_type::Symbol)
      @ Transformers.HuggingFace ~/.julia/packages/Transformers/qH1VW/src/huggingface/models/models.jl:35
```

**Comment by deveshjawla** [comment]
Hi Peter,

Thank you for the advice. It was indeed a problem that the `using Transformers` in [HugginFaceValidation/main.jl](url) was using the Transformers package from the web (which does not have the DistilBert implementation yet). 

To use the local Transformers with a DistilBert implementation including the following lines in the [HugginFaceValidation/main.jl](url) works!!
````
include("./../../src/Transformers.jl")
using .Transformers
using .Transformers.HuggingFace
````

So now to run validation I can do:
`julia --project example/HuggingFaceValidation/main.jl -s based_model distilbert/distilbert-base-cased`

Let me know your thoughts. Thank you.

**Comment by chengchingwen** [comment]
You can use the ["develop" functionality of Pkg.jl](https://pkgdocs.julialang.org/v1/managing-packages/#developing) like this:

```
some/path/to/this/HuggingFaceValidation$ julia --project
julia>]
(HuggingFaceValidation) pkg> dev ../../
```

This will force the `Manifest.toml` to use your local modified package, then the modification you did won't be needed.

**Comment by deveshjawla** [comment]
Oh Thank you again!!
Much appreciated!!
I will update these things and create a pull request.
