### ISSUE TITLE
HuggingFace example

### ISSUE THREAD

**Issue by lincolnhannah** [chengchingwen/Transformers.jl#205]
Could you add an example of downloading a HuggingFace model and querying it.   "What is the capital of France?"
or some other simple question.

**Comment by chengchingwen** [comment]
https://github.com/chengchingwen/Transformers.jl/blob/master/example/Dolly_example.ipynb

Does this example work for you?

**Comment by lincolnhannah** [comment]
was able to run GPT2 example.  Many thanks :)
