### ISSUE TITLE
Support  gpu with julia v1.6 

### ISSUE THREAD

**Issue by zsz00** [chengchingwen/Transformers.jl#49]
Hope to support julia v1.6

**Comment by chengchingwen** [comment]
1.6 is supported with v0.1.8

**Comment by chengchingwen** [comment]
Right now the gpu part seems to failed, but cpu part should work fine

**Comment by chengchingwen** [comment]
Running `softmax` with CUDA v2.6.2 and NNlib v0.7.17 result in wrong values, but this is fixed on their master. We will need to halt gpu support until they tag new release.

**Comment by chengchingwen** [comment]
Should be fix by v0.1.12
