### ISSUE TITLE
Update Compat

### ISSUE THREAD

**Issue by lazarusA** [chengchingwen/Transformers.jl#62]
Hi,
when installing Transformers the following main downgrades happens: (this is in Julia 1.6, it works but not with the latest versions)

Flux v0.12.3 ⇒ v0.12.1
CUDA v3.2.1 ⇒ v2.6.3
DataStructures v0.18.9 ⇒ v0.17.20
Flux v0.12.3 ⇒ v0.12.1

any change to increase compatibility with the latest releases ? 

cheers!

**Comment by chengchingwen** [comment]
Should be solved with the new release
