### ISSUE TITLE
ERROR : downloading  on m1 1.7 beta 3

### ISSUE THREAD

**Issue by rcherukuri12** [chengchingwen/Transformers.jl#76]
I keep getting this error:
[ Info: loading pretrain bert model: scibert_basevocab_uncased.tfbson 
ERROR: type DataType has no field mutable

no matter what model type I pick.

**Comment by rcherukuri12** [comment]
Any info on this problem ?

**Comment by chengchingwen** [comment]
Probably because currently we don't support 1.7 but I haven't test it yet.

**Comment by chengchingwen** [comment]
You would need to update to BSON v0.3.4 for working with Julia v1.7
https://github.com/JuliaIO/BSON.jl/pull/99
