### ISSUE TITLE
Support for HuggingFace bert-base-portuguese-cased

### ISSUE THREAD

**Issue by storopoli** [chengchingwen/Transformers.jl#78]
Is it possible to support the [`neuralmind/bert-base-portuguese-cased`](https://huggingface.co/neuralmind/bert-base-portuguese-cased)? We are doing lots of portuguese NLP and this custom BERT model has better performance in our portuguese NLP problems.

Cc'ing a collaborator @RosalRicardo

**Comment by dcecchini** [comment]
I also wish to have the portuguese models available in Julia. Is there any plan to add those? Or a tutorial where we can transform them by ourselves? 

I tried to use the [Transformers.BidirectionalEncoder.tfckpt2bson](https://chengchingwen.github.io/Transformers.jl/dev/bert/#Transformers.BidirectionalEncoder.tfckpt2bson) but it needs `TensorFlow.jl` installed, a package that is not maintained anymore and not compatible with Windows: 

![image](https://user-images.githubusercontent.com/11304253/174840680-7300b8ac-894b-4103-9c1f-f95ac31f5d68.png)

**Comment by chengchingwen** [comment]
Yes, that's on the plan (#83). I'm currently working on fixing the hugginface part so that would be supported in near future. Also the `tfckpt2bson` would eventually be removed.
